### ISSUE TITLE
SerialCraft Mod source code?

### ISSUE THREAD

**Issue by radames** [CMBSTEAMlab/serialcraft-arduino#1]
Are you releasing the serialcraft forge mod as open source?
thanks

**Comment by jallwine** [comment]
Yeah, I'd like to. I'm not too familiar with the Minecraft forge/eclipse setup, so I haven't gotten around to getting a nice clean repository together. I'll update this when I get it going.

**Comment by radames** [comment]
great! They have a nice tutorial how to use gradle, http://www.minecraftforge.net/forum/index.php?topic=14048.0 maybe could be a good way to share the project

**Comment by jallwine** [comment]
https://github.com/AllwineDesigns/SerialCraftMod
